from __future__ import annotations
from pathlib import Path
from typing import Any, Dict

DESCRIPTION = "PPT 生成适配入口"
ICON = "📊"


def execute(title: str = "Auto PPT", output: str = "", user_input: str = "", **kwargs) -> Dict[str, Any]:
    try:
      from pptx import Presentation
    except Exception:
      return {"status": "error", "code": "missing_dependency", "message": "python-pptx not installed"}

    out = (output or "d:/jarvis/workspace/auto_generated.pptx").strip()
    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title or user_input or "Auto PPT"
    if slide.placeholders and len(slide.placeholders) > 1:
      slide.placeholders[1].text = "Generated by pptx-generator adapter"
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    prs.save(out)
    return {"status": "success", "output": out, "notes": "pptx_generated"}
