"""Tool schema definitions for the core tool system."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Literal


@dataclass(frozen=True)
class ToolSpec:
    """Structured specification for a tool registered in ToolRegistry.

    LLM can see: name, description, input_schema, output_schema, risk_level, permissions.
    LLM CANNOT see: handler.
    """

    name: str
    description: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    risk_level: Literal["low", "medium", "high", "blocked"]
    requires_approval: bool
    permissions: set[str]
    allowed_in_modes: set[str] = field(default_factory=lambda: {"safe", "ask", "edit"})
    handler: Callable | None = field(default=None, repr=False)

    def to_llm_summary(self) -> dict[str, Any]:
        """Return a description visible to the LLM (no handler)."""
        return {
            "name": self.name,
            "description": self.description,
            "input_schema": self.input_schema,
            "output_schema": self.output_schema,
            "risk_level": self.risk_level,
            "requires_approval": self.requires_approval,
            "permissions": sorted(self.permissions),
        }

    def to_dict(self) -> dict[str, Any]:
        """Full serialization including all fields."""
        return {
            "name": self.name,
            "description": self.description,
            "input_schema": self.input_schema,
            "output_schema": self.output_schema,
            "risk_level": self.risk_level,
            "requires_approval": self.requires_approval,
            "permissions": sorted(self.permissions),
            "allowed_in_modes": sorted(self.allowed_in_modes),
        }


@dataclass
class ToolCall:
    """A tool invocation request — generated by the LLM or planner."""

    tool_name: str
    arguments: dict[str, Any]
    reason: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool_name": self.tool_name,
            "arguments": self.arguments,
            "reason": self.reason,
        }


@dataclass
class ToolResult:
    """Structured result from tool execution."""

    tool_name: str
    ok: bool
    output: str | dict | list | None = None
    error: str | None = None
    risk_level: str = "low"
    requires_approval: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool_name": self.tool_name,
            "ok": self.ok,
            "output": self.output,
            "error": self.error,
            "risk_level": self.risk_level,
            "requires_approval": self.requires_approval,
            "metadata": self.metadata,
        }


@dataclass
class ToolContext:
    """Runtime context passed to tool handlers."""

    workspace_root: str = "."
    mode: str = "safe"
    permission_mode: str = "read_only"
    session_id: str = ""
    request_id: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
