"""Jarvis Core Phase 1 foundational modules."""

from .command_runner import CommandRunner
from .checkpoint_manager import CheckpointManager
from .failure_analyzer import FailureAnalyzer
from .file_editor import FileEditor
from .jarvis_rules_loader import JarvisRulesLoader
from .repo_reader import RepoReader
from .safety_guard import SafetyGuard
from .task_runtime import TaskRuntime
from .test_runner import TestRunner
from .tool_router import ToolRouter
from .control_surface import ControlSurface
from .data_outlets import DataOutlets
from .view_models import (
    REVIEW_PANE_UI_CONTRACT_VERSION,
    REVIEW_PANE_UI_PRIORITY_FIELDS,
    build_channels_summary_view,
    build_checkpoint_review_view,
    build_gate_summary_view,
    build_gateway_summary_view,
    build_latest_test_result_view,
    build_nodes_summary_view,
    build_operator_dashboard_view,
    build_review_summary_view,
    build_run_detail_view,
    build_run_list_view,
    build_run_skill_hits_view,
    build_run_step_trace_view,
    build_run_stop_summary_view,
    build_run_tool_calls_view,
    build_release_gate_summary_view,
    build_review_pane_view,
    build_task_summary_view,
    build_task_timeline_view,
    view_model_bundle,
)
from .output_compressor import OutputCompressor
from .release_gate_store import (
    merge_gate_views,
    read_acceptance_summary,
    read_release_gate_summary,
    write_acceptance_summary,
    write_release_gate_summary,
)
from .runtime_snapshot import load_runtime_snapshot, save_runtime_snapshot
from .control_http_adapter import make_handler, run_http_server
from .phase3_real_task_flow import run_real_task_flow
from .app_web_sdk_adapter import (
    BridgeParseError,
    parse_bridge_payload,
    SUPPORTED_SCHEMA_ID,
    MIN_SCHEMA_VERSION,
    MIN_PAYLOAD_VERSION,
    SdkInputModel,
)
from .gateway_state import (
    GATEWAY_VERSION,
    GATEWAY_PROTOCOL_VERSION,
    Gateway,
    GatewayEvent,
    GatewayEventStream,
    GatewayReadOnlyAPI,
    GatewayState,
    bind_gateway,
)
from .react_readiness import (
    HeavyReActRuntime,
    HeavyReActConfig,
    RuntimeState,
    StepTrace,
    RunResult,
)
from .skill_harness import (
    SkillEntry,
    SkillMatch,
    SkillHitRecord,
    SkillRecord,
    SkillSelectionResult,
    SkillRegistry,
    get_skill_registry,
    SkillLoader,
    SkillMatcher,
    select_skills_for_task,
    execute_skill,
    SkillContextAssembler,
    SkillHitLogger,
)
from .routing import (
    DomainClassifier,
    IntentRouter,
    PolicySkillSelector,
    IntentPolicyRouter,
    DomainRouteResult,
    IntentRouteResult,
    PolicySelectionResult,
    RouteResultBundle,
)
from .policy import ApprovalRiskMatrix

__all__ = [
    "RepoReader",
    "FileEditor",
    "CommandRunner",
    "CheckpointManager",
    "TestRunner",
    "TaskRuntime",
    "FailureAnalyzer",
    "JarvisRulesLoader",
    "SafetyGuard",
    "OutputCompressor",
    "ToolRouter",
    "ControlSurface",
    "DataOutlets",
    "write_release_gate_summary",
    "write_acceptance_summary",
    "read_release_gate_summary",
    "read_acceptance_summary",
    "merge_gate_views",
    "save_runtime_snapshot",
    "load_runtime_snapshot",
    "make_handler",
    "run_http_server",
    "run_real_task_flow",
    "build_task_summary_view",
    "REVIEW_PANE_UI_CONTRACT_VERSION",
    "REVIEW_PANE_UI_PRIORITY_FIELDS",
    "build_task_timeline_view",
    "build_latest_test_result_view",
    "build_checkpoint_review_view",
    "build_release_gate_summary_view",
    "build_review_pane_view",
    "build_run_list_view",
    "build_run_detail_view",
    "build_run_step_trace_view",
    "build_run_skill_hits_view",
    "build_run_tool_calls_view",
    "build_run_stop_summary_view",
    "build_gateway_summary_view",
    "build_channels_summary_view",
    "build_nodes_summary_view",
    "build_review_summary_view",
    "build_gate_summary_view",
    "build_operator_dashboard_view",
    "view_model_bundle",
    "BridgeParseError",
    "parse_bridge_payload",
    "SUPPORTED_SCHEMA_ID",
    "MIN_SCHEMA_VERSION",
    "MIN_PAYLOAD_VERSION",
    "SdkInputModel",
    "GATEWAY_VERSION",
    "GATEWAY_PROTOCOL_VERSION",
    "Gateway",
    "GatewayEvent",
    "GatewayEventStream",
    "GatewayReadOnlyAPI",
    "GatewayState",
    "bind_gateway",
    "HeavyReActRuntime",
    "HeavyReActConfig",
    "RuntimeState",
    "StepTrace",
    "RunResult",
    "SkillEntry",
    "SkillMatch",
    "SkillHitRecord",
    "SkillRecord",
    "SkillSelectionResult",
    "SkillRegistry",
    "get_skill_registry",
    "SkillLoader",
    "SkillMatcher",
    "select_skills_for_task",
    "execute_skill",
    "SkillContextAssembler",
    "SkillHitLogger",
    "DomainClassifier",
    "IntentRouter",
    "PolicySkillSelector",
    "IntentPolicyRouter",
    "DomainRouteResult",
    "IntentRouteResult",
    "PolicySelectionResult",
    "RouteResultBundle",
    "ApprovalRiskMatrix",
]
